[tools]
aichat = "0.29.0"
atuin = "latest"
bat = "latest"
bun = "1.3.5"
cmake = "latest"
delta = "latest"
dust = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gum = "latest"
jq = "latest"
lazygit = "latest"
node = "22"
pnpm = "latest"
ripgrep = "latest"
rust = "latest"
starship = "latest"
tmux = "latest"
usage = "latest"
uv = "latest"
yazi = "latest"
zoxide = "latest"
